// 导入文件读取接口。
import { readFileSync } from 'node:fs';
// 导入隔离执行接口。
import { runInNewContext } from 'node:vm';
// 导入断言接口。
import assert from 'node:assert/strict';
// 使用项目锁定的 TypeScript 转译当前源码。
import ts from 'typescript';
// 收集源码注册的事件处理器。
const handlers = new Map();
// 收集样式、剪贴板和文章操作。
const observed = { styles: '', clipboard: '', articleStyleRemoved: false, gateRemoved: false };
// 模拟线上脚本生成的工具栏父节点，代码正文是工具栏的兄弟节点。
const button = { parentNode: { innerText: '运行' }, setAttribute: noop, removeAttribute: noop, addEventListener: registerHandler };
// Purpose: 保存当前源码注册的处理器；Generated by Codex。
function registerHandler(type, handler) {
  // 记录事件供定向复现调用。
  handlers.set(type, handler);
// 结束事件注册函数。
}
// Purpose: 捕获源码生成的样式；Generated by Codex。
function captureStyle(value) {
  // 保存完整样式字符串。
  observed.styles = value;
// 结束样式捕获函数。
}
// Purpose: 捕获源码传给油猴的剪贴板文本；Generated by Codex。
function captureClipboard(value) {
  // 保存实际复制参数。
  observed.clipboard = value;
// 结束剪贴板捕获函数。
}
// Purpose: 模拟文章容器属性移除；Generated by Codex。
function removeArticleStyle() {
  // 标记容器样式被移除。
  observed.articleStyleRemoved = true;
// 结束属性移除函数。
}
// Purpose: 模拟尚未获取全文的文章展开入口；Generated by Codex。
function removeGate() {
  // 标记原始入口被删除。
  observed.gateRemoved = true;
// 结束入口删除函数。
}
// Purpose: 提供当前源码需要的 class 查询；Generated by Codex。
function getElementsByClassName(name) {
  // 返回复制按钮或未获取全文时仍需保留的入口。
  return name === 'hljs-button' ? [button] : name === 'hide-article-box' ? [{ remove: removeGate }] : [];
// 结束 class 查询函数。
}
// Purpose: 提供当前源码需要的 ID 查询；Generated by Codex。
function getElementById(name) {
  // 返回文章容器。
  return name === 'article_content' ? { removeAttribute: removeArticleStyle } : null;
// 结束 ID 查询函数。
}
// Purpose: 提供本次探针不涉及的空单节点查询；Generated by Codex。
function querySelector() {
  // 不在此探针模拟克隆行为。
  return null;
// 结束单节点查询函数。
}
// Purpose: 提供本次探针不涉及的空多节点查询；Generated by Codex。
function querySelectorAll() {
  // 不在此探针模拟代码折叠与行号。
  return [];
// 结束多节点查询函数。
}
// Purpose: 替代本次探针不需要的定时与冒泡操作；Generated by Codex。
function noop() {
  // 返回稳定的模拟定时器编号。
  return 0;
// 结束空操作函数。
}
// 读取原始源码，保持业务实现不变。
const source = readFileSync(new URL('./main.ts', import.meta.url), 'utf8');
// 移除模块导入，新拦截器由独立测试覆盖。
const compiled = ts.transpile(source.replace(/^import .* from .*\r?\n/gm, ''), { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None });
// 模拟页面已加载，仅验证原有文章增强逻辑。
await runInNewContext(compiled, { document: { readyState: 'complete', querySelector, querySelectorAll, getElementsByClassName, getElementById }, unsafeWindow: {}, installLoginGuard: noop, GM_addStyle: captureStyle, GM_setClipboard: captureClipboard, clearTimeout: noop, setTimeout: noop, console });
// 调用源码实际注册的点击处理器。
handlers.get('click')({ stopPropagation: noop });
// 确认已复现复制工具栏而非代码正文的缺陷。
assert.equal(observed.clipboard, '运行');
// 确认样式优先级仍被写成独立无效声明。
assert.match(observed.styles, /user-select: auto;\s*!important;/);
// 确认源码不作内容完整性判断就移除容器样式。
assert.equal(observed.articleStyleRemoved, true);
// 确认源码无条件删除已有展开入口。
assert.equal(observed.gateRemoved, true);
// 输出探针边界与复现结果，避免误称浏览器功能通过。
console.log(JSON.stringify({ kind: 'source-level probes with DOM stubs, not browser E2E', reproduced: ['toolbar text copied', 'invalid important declaration', 'article gate removed unconditionally'], observed }, null, 2));
