// 导入断言工具。
import assert from 'node:assert/strict';
// 导入源码读取工具。
import { readFileSync } from 'node:fs';
// 导入隔离执行工具。
import { runInNewContext } from 'node:vm';
// 导入项目已有的 TypeScript 转译器。
import ts from 'typescript';
// 读取实际拦截器源码。
const source = readFileSync(new URL('./login-guard.ts', import.meta.url), 'utf8');
// 转译为可在隔离上下文执行的代码。
const compiled = ts.transpile(source.replace('export function', 'function'), { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None });
// 保存模拟时间与实际调用。
let now = 10000, click, calls = 0;
// Purpose: Simulate a login control for policy tests. Generated by Codex
class Control {
  // 保存入口名称。
  textContent = '登录';
  // Purpose: Represent a clickable element. Generated by Codex
  matches() { return true; }
  // Purpose: Provide absent optional labels. Generated by Codex
  getAttribute() { return null; }
// 结束元素模拟。
}
// Purpose: Record the original login call and receiver. Generated by Codex
function original(...args) { calls++; return { receiver: this, args }; }
// Purpose: Capture the actual trusted-intent listener. Generated by Codex
function addEventListener(type, handler) { assert.equal(type, 'click'); click = handler; }
// Purpose: Supply deterministic time for expiry tests. Generated by Codex
function clock() { return now; }
// 创建隔离上下文。
const context = { Element: Control, Date: { now: clock } };
// 加载真正的拦截器函数。
runInNewContext(compiled, context);
// 从空命名空间开始，模拟 document-start。
const page = {};
// 安装拦截器。
context.installLoginGuard(page, { addEventListener });
// 模拟网站延迟初始化。
page.csdn = {};
// 模拟网站创建登录组件。
page.csdn.loginBox = { show: original, key: original, showTip: original, showAutoTip: original, close: original };
// 创建登录按钮。
const control = new Control();
// Purpose: Return the activated control path. Generated by Codex
function composedPath() { return [control]; }
// Purpose: Simulate the browser's trusted-event signal. Generated by Codex
function activate(trusted = true) { click({ isTrusted: trusted, composedPath }); }
// 覆盖四种弹窗入口。
for (const method of ['show', 'key', 'showTip', 'showAutoTip']) {
  // 无用户意图的滚动、计时、复制调用全部被拦截。
  assert.equal(page.csdn.loginBox[method]({}), undefined);
  // 伪造点击不能授权。
  activate(false);
  // 验证程序点击仍被拦截。
  assert.equal(page.csdn.loginBox[method]({}), undefined);
  // 模拟手动登录。
  activate();
  // 自动标记即使恰逢手动点击也不能放行。
  assert.equal(page.csdn.loginBox[method]({ reportExtra: { autoPopup: true } }), undefined);
  // 保留一次手动调用及其参数。
  const options = { cb: original };
  // 执行手动调用。
  const result = page.csdn.loginBox[method](options);
  // 验证接收者保持不变。
  assert.equal(result.receiver, page.csdn.loginBox);
  // 验证参数保持原对象。
  assert.equal(result.args[0], options);
  // 验证授权只能使用一次。
  assert.equal(page.csdn.loginBox[method]({}), undefined);
// 结束入口覆盖。
}
// 确认只有四次手动调用执行。
assert.equal(calls, 4);
// 模拟无关点击。
control.textContent = '复制代码';
// 派发真实普通点击。
activate();
// 普通点击不允许弹窗。
assert.equal(page.csdn.loginBox.show(), undefined);
// 恢复登录入口。
control.textContent = '登录';
// 记录手动意图。
activate();
// 推进时间超过授权窗口。
now += 1501;
// 过期意图不能放行。
assert.equal(page.csdn.loginBox.show(), undefined);
// 模拟单个方法被网站重新赋值。
page.csdn.loginBox.show = original;
// 验证新方法仍受到拦截。
assert.equal(page.csdn.loginBox.show(), undefined);
// 模拟整个命名空间重新初始化。
page.csdn = { loginBox: { show: original, close: original } };
// 验证新组件仍受到拦截。
assert.equal(page.csdn.loginBox.show(), undefined);
// 验证关闭方法不被包装。
assert.equal(page.csdn.loginBox.close, original);
// 验证组件重载后手动入口可用。
activate();
// 验证原返回值仍保留。
assert.equal(page.csdn.loginBox.show().receiver, page.csdn.loginBox);
// 输出测试范围。
console.log('PASS: 4 login APIs; automatic and synthetic calls; explicit login; one-shot/expiry; receiver/arguments; method and namespace replacement. Mock policy tests, not browser E2E.');
