// 描述页面对象的动态属性。
type PageObject = Record<string, unknown>
// Purpose: Install automatic login suppression while preserving explicit login actions. Generated by Codex
export function installLoginGuard(page: PageObject, doc: Document): void {
  // 保存一次手动登录授权的截止时间。
  let manualUntil = 0
  // 记录已处理对象，避免重复包装。
  const watched = new WeakMap<object, Set<string>>()
  // Purpose: Recognize trusted activation of a login or registration control. Generated by Codex
  function rememberLogin(event: Event): void {
    // 仅接受真实用户事件，并在每次点击时撤销旧授权。
    manualUntil = 0
    // 忽略程序触发的点击。
    if (!event.isTrusted) return
    // 从事件路径识别入口，支持图标和影子树内按钮。
    for (const target of event.composedPath()) {
      // 跳过非元素节点。
      if (!(target instanceof Element)) continue
      // 仅读取可点击入口，避免父容器文字误匹配。
      if (!target.matches('a, button, [role="button"], [onclick], .toolbar-btn-login, #csdn-toolbar-profile')) continue
      // 合并入口的可见文字和无障碍名称。
      const label = `${target.getAttribute('aria-label') || ''} ${target.getAttribute('title') || ''} ${target.textContent || ''}`.trim()
      // 支持中文登录注册和英文入口，拒绝大段正文。
      if (label.length <= 80 && /登录|登陆|注册|\blog\s*in\b|\bsign\s*(in|up)\b/i.test(label)) {
        // 为异步登录处理保留短暂的一次性授权。
        manualUntil = Date.now() + 1500
        // 找到入口后停止遍历。
        return
      // 结束入口判定。
      }
    // 结束事件路径遍历。
    }
  // 结束手动意图记录。
  }
  // 在站点点击处理器之前识别登录意图；键盘激活按钮同样产生点击。
  doc.addEventListener('click', rememberLogin, true)
  // Purpose: Watch current and later property assignments without polling. Generated by Codex
  function watch(owner: PageObject, key: string, transform: (value: unknown) => unknown): void {
    // 查询对象的已处理属性。
    const keys = watched.get(owner) || new Set<string>()
    // 避免重复安装访问器。
    if (keys.has(key)) return
    // 保存处理记录。
    watched.set(owner, keys)
    // 记录属性名称。
    keys.add(key)
    // 保留原属性特征。
    const descriptor = Object.getOwnPropertyDescriptor(owner, key)
    // 不改写网站已有访问器或不可配置属性。
    if (descriptor && (!descriptor.configurable || descriptor.get || descriptor.set)) return
    // 包装已经存在的值。
    let value = transform(owner[key])
    // 同步拦截后续赋值，避免延迟加载的竞态。
    Object.defineProperty(owner, key, {
      // 允许网站正常重新定义属性。
      configurable: true,
      // 保持枚举行为。
      enumerable: descriptor?.enumerable ?? true,
      // Purpose: Return the guarded property value. Generated by Codex
      get() { return value },
      // Purpose: Guard replacement values immediately. Generated by Codex
      set(next: unknown) { value = transform(next) },
    // 完成属性监听。
    })
  // 结束属性监听函数。
  }
  // Purpose: Wrap all known CSDN login presentation methods. Generated by Codex
  function guardBox(value: unknown): unknown {
    // 保留尚未初始化或无效的组件值。
    if (!value || typeof value !== 'object') return value
    // 转换为页面组件对象。
    const box = value as PageObject
    // 覆盖弹窗、提示和快捷登录四种入口。
    for (const method of ['show', 'showTip', 'showAutoTip', 'key']) {
      // Purpose: Wrap each assigned presentation function. Generated by Codex
      watch(box, method, function wrap(original: unknown): unknown {
        // 非函数赋值保持原样。
        if (typeof original !== 'function') return original
        // Purpose: Block unsolicited calls and preserve authorized call semantics. Generated by Codex
        return function guarded(this: unknown, ...args: unknown[]): unknown {
          // 读取站点显式自动提示标记。
          const options = args[0] as { reportExtra?: { autoPopup?: unknown } } | undefined
          // 明确标记的自动提示不能消耗手动授权。
          if (options?.reportExtra?.autoPopup) return undefined
          // 没有手动登录意图的调用全部拦截。
          if (Date.now() >= manualUntil) return undefined
          // 放行一次后立即撤销授权。
          manualUntil = 0
          // 保留接收者、参数、返回值和原函数异常。
          return Reflect.apply(original, this, args)
        // 结束调用包装。
        }
      // 完成方法包装。
      })
    // 结束方法遍历。
    }
    // 保留组件对象身份以及关闭等其他方法。
    return value
  // 结束组件包装。
  }
  // Purpose: Attach the guard to present and future CSDN namespaces. Generated by Codex
  function guardNamespace(value: unknown): unknown {
    // 仅监听已经初始化的命名空间对象。
    if (value && typeof value === 'object') watch(value as PageObject, 'loginBox', guardBox)
    // 保留命名空间对象身份。
    return value
  // 结束命名空间包装。
  }
  // 尽早监听命名空间赋值，不依赖定时轮询。
  watch(page, 'csdn', guardNamespace)
// 结束自动登录拦截安装。
}
