// 导入油猴样式、剪贴板和页面窗口接口。
import { GM_addStyle, GM_setClipboard, unsafeWindow } from '$'
// 导入自动登录拦截器。
import { installLoginGuard } from './login-guard'

// 在站点初始化登录组件之前安装拦截器。
installLoginGuard(unsafeWindow as unknown as Record<string, unknown>, document)

// Purpose: Preserve paid article controls before applying article enhancements. Modified by Codex
async function main() {
  //去除登录框
  // GM_addStyle(".passport-login-container{display:none!important;}");

  // Purpose: 生成有效的文本选择优先级声明；Modified by Codex。
  function style_selectable(selector: string): string {
    // 将优先级直接附加到属性值，覆盖站点禁止选择样式。
    return `${selector} { -webkit-user-select: auto !important; user-select: auto !important; }`
  // 结束选择样式生成函数。
  }
  GM_addStyle(
    style_selectable('#content_views')
    + style_selectable('#content_views pre')
    + style_selectable('#content_views pre code')
  )

  // 删除页面的ID，使其不关联相关事件
  //document.getElementById('content_views')?.setAttribute('id','')
  //document.getElementById('article_content')?.setAttribute('id','')

  // 付费正文不可通过取消折叠补全，提前退出以保留原节点及购买事件。
  if (hasPaidArticleGate()) return

  // 使用cloneNode复制一遍.blog-content-box去除js赋值的处理程序
  let contentEl = document.querySelector('main .blog-content-box')
  contentEl?.parentNode?.replaceChild(contentEl.cloneNode(true), contentEl)
  document.querySelectorAll('.pre-numbering')?.forEach(e => e.removeAttribute('style')) // 显示由于clone blog-content-box导致的代码行号动画未执行而不显示

  // 展开折叠的代码
  // test: 需要展开代码的网址 https://blog.csdn.net/lxlyx11/article/details/124961664
  document.querySelectorAll('.set-code-hide').forEach(e => e.classList.replace('set-code-hide', 'set-code-show')) //移除折叠样式
  document.querySelectorAll('.hide-preCode-box').forEach(e => e.remove())   //移除下拉箭头

  // 初始化当前按钮的提示并移除内联复制入口。
  prepareCopyButtons()
  // 安装一次捕获监听，兼容 CSDN 后续动态生成或替换的按钮。
  installCopyHandler()

  // 展开需要关注博主阅读全文的内容
  // test: 需要订阅专栏的网址 https://blog.csdn.net/uote_e/article/details/131385801
  document.getElementById('article_content')?.removeAttribute("style")
  document.getElementsByClassName('hide-article-box')[0]?.remove()
}

// Purpose: Prepare existing code copy buttons before delegated handling. Generated by Codex
function prepareCopyButtons(): void {
  // 遍历当前页面已经存在的复制按钮。
  document.querySelectorAll('.hljs-button').forEach(button => {
    // 统一按钮提示文字。
    button.setAttribute('data-title', 'Copy code')
    // 删除页面内联复制逻辑，避免重复处理。
    button.removeAttribute('onclick')
  // 处理当前代码节点或完成当前分支。
  })
// 结束按钮初始化函数。
}

// Purpose: Handle code copy clicks before page handlers and dynamic replacement. Generated by Codex
function installCopyHandler(): void {
  // 使用模块级标记避免重复安装文档监听器。
  if (copyHandlerInstalled) return
  // 标记监听器已经安装。
  copyHandlerInstalled = true
  // 在捕获阶段拦截页面原有复制处理。
  document.addEventListener('click', handleCopyClick, true)
// 结束复制监听安装函数。
}

// Purpose: Copy the code block associated with the clicked button. Generated by Codex
function handleCopyClick(event: Event): void {
  // 将事件目标限定为复制按钮自身或其子节点。
  const target = event.target as { closest?: (selector: string) => Element | null } | null
  // 处理当前代码节点或完成当前分支。
  const button = target?.closest?.('.hljs-button') ?? null
  // 非代码复制按钮交由页面原逻辑处理。
  if (!button) return
  // 阻止 CSDN 内联及冒泡复制逻辑覆盖结果。
  event.preventDefault()
  // 处理当前代码节点或完成当前分支。
  event.stopImmediatePropagation()
  // 读取当前按钮对应的代码文本。
  const code = getCodeText(button)
  // 通过油猴权限写入系统剪贴板。
  GM_setClipboard(code, 'text')
  // 显示当前按钮的成功状态。
  button.setAttribute('data-title', 'Copied!')
  // 清理当前按钮之前的提示定时器。
  const previousTimer = copyTimers.get(button)
  // 处理当前代码节点或完成当前分支。
  if (previousTimer !== undefined) clearTimeout(previousTimer)
  // 设置当前按钮的提示恢复定时器。
  const timer = setTimeout(() => {
    // 处理当前代码节点或完成当前分支。
    button.setAttribute('data-title', 'Copy code')
    // 处理当前代码节点或完成当前分支。
    copyTimers.delete(button)
  // 处理当前代码节点或完成当前分支。
  }, 1000)
  // 保存当前按钮的定时器。
  copyTimers.set(button, timer)
// 结束复制点击处理函数。
}

// Purpose: Extract only the code block text associated with a copy button. Generated by Codex
function getCodeText(button: Element): string {
  // 优先检查按钮位于 pre 内的特殊结构。
  const ownPre = button.closest('pre')?.querySelector('code')
  // 处理当前代码节点或完成当前分支。
  if (ownPre) return readCodeText(ownPre)
  // 从按钮向上检查每一层容器的相邻代码块。
  let current: Element | null = button
  // 处理当前代码节点或完成当前分支。
  for (let level = 0; current && level < 12; level++, current = current.parentElement) {
    // 取得当前容器的直接子节点，避免跨多个代码块取第一个后代。
    const children = Array.from(current.children)
    // 找到按钮所在的直接子容器。
    const childIndex = children.findIndex(child => child === button || child.contains(button))
    // 在按钮后方优先查找最近的代码块。
    for (const sibling of children.slice(childIndex + 1)) {
      // 处理当前代码节点或完成当前分支。
      const code = sibling.matches('pre') ? sibling.querySelector('code') : sibling.querySelector('pre code, code')
      // 处理当前代码节点或完成当前分支。
      if (code) return readCodeText(code)
    // 处理当前代码节点或完成当前分支。
    }
    // 按钮后方没有代码时，再检查前方同级代码块。
    for (const sibling of children.slice(0, childIndex).reverse()) {
      // 处理当前代码节点或完成当前分支。
      const code = sibling.matches('pre') ? sibling.querySelector('code') : sibling.querySelector('pre code, code')
      // 处理当前代码节点或完成当前分支。
      if (code) return readCodeText(code)
    // 处理当前代码节点或完成当前分支。
    }
  // 处理当前代码节点或完成当前分支。
  }
  // 找不到代码节点时返回空文本，避免复制工具栏文案。
  return ''
// 处理当前代码节点或完成当前分支。
}

// Purpose: Preserve rendered line breaks when CSDN splits code into child nodes. Generated by Codex
function readCodeText(code: Element): string {
  // 优先读取浏览器根据换行和块级节点计算出的文本。
  const renderedText = (code as HTMLElement).innerText
  // 处理当前代码节点或完成当前分支。
  if (renderedText) return renderedText
  // 在测试环境或不可见节点中回退到原始文本节点内容。
  return code.textContent ?? ''
// 处理当前代码节点或完成当前分支。
}

// 记录复制监听器是否已经安装。
let copyHandlerInstalled = false
// 记录每个按钮的提示恢复定时器。
const copyTimers = new WeakMap<Element, number>()

// Purpose: Detect paid reading gates without matching VIP mentions in article text. Generated by Codex
function hasPaidArticleGate(): boolean {
  // 识别实际页面的付费遮罩和购买入口，避免正文或侧栏中的 VIP 字样误判。
  if (document.querySelector('.hide-article-box .vip-mask, .hide-article-box .openvippay, .hide-article-box #getVipUrl')) return true
  // 遍历全部阅读入口，兼容同页存在多个遮罩。
  for (const gate of Array.from(document.querySelectorAll('.hide-article-box'))) {
    // 文本节点自动解码 HTML 实体，另兼容直接显示的实体及不换行空格。
    const text = (gate.textContent ?? '').replace(/&(?:#x0*a0|#0*160|nbsp);/gi, ' ').replace(/\s+/g, '')
    // 价格、解锁、付费专栏或会员提示均保留，不依赖固定的每日价格。
    if (/解锁|付费|付钱|充值|购买|订阅|开通|续费|VIP|会员|\d+(?:\.\d+)?元/i.test(text)) return true
  // 结束入口检查。
  }
  // 未发现付费入口时沿用原有文章增强。
  return false
// 结束付费入口识别函数。
}

// Purpose: Run existing article enhancements after the page has loaded. Generated by Codex
function startArticle(): void {
  // 保留原有文章增强逻辑的异常处理。
  main().catch(reportError)
// 结束文章启动函数。
}
// Purpose: Report article enhancement failures. Modified by Codex
function reportError(err: unknown): void {
  // 输出原有错误信息。
  console.error(err)
// 结束错误处理函数。
}
// 页面已经加载时直接启动，否则等待页面加载以兼容原来的运行时机。
if (document.readyState === 'complete') startArticle()
// 注册一次性的加载回调。
else window.addEventListener('load', startArticle, { once: true })
