// 导入油猴样式、剪贴板和页面窗口接口。
import { GM_addStyle, GM_setClipboard, unsafeWindow } from '$'
// 导入自动登录拦截器。
import { installLoginGuard } from './login-guard'

// 在站点初始化登录组件之前安装拦截器。
installLoginGuard(unsafeWindow as unknown as Record<string, unknown>, document)

async function main() {
  //去除登录框
  // GM_addStyle(".passport-login-container{display:none!important;}");

  // 设置文字为可选
  function style_selectable(selector: string): string {
    return selector + " {\
    -webkit-touch-callout: auto;\
    -webkit-user-select: auto;\
    -khtml-user-select: auto;\
    -moz-user-select: auto;\
    -ms-user-select: auto;\
    user-select: auto;\
    !important;\
  }"
  }
  GM_addStyle(
    style_selectable('#content_views')
    + style_selectable('#content_views pre')
    + style_selectable('#content_views pre code')
  )

  // 删除页面的ID，使其不关联相关事件
  //document.getElementById('content_views')?.setAttribute('id','')
  //document.getElementById('article_content')?.setAttribute('id','')

  // 使用cloneNode复制一遍.blog-content-box去除js赋值的处理程序
  let contentEl = document.querySelector('main .blog-content-box')
  contentEl?.parentNode?.replaceChild(contentEl.cloneNode(true), contentEl)
  document.querySelectorAll('.pre-numbering')?.forEach(e => e.removeAttribute('style')) // 显示由于clone blog-content-box导致的代码行号动画未执行而不显示

  // 展开折叠的代码
  // test: 需要展开代码的网址 https://blog.csdn.net/lxlyx11/article/details/124961664
  document.querySelectorAll('.set-code-hide').forEach(e => e.classList.replace('set-code-hide', 'set-code-show')) //移除折叠样式
  document.querySelectorAll('.hide-preCode-box').forEach(e => e.remove())   //移除下拉箭头

  // 遍历登陆复制按钮并修改属性
  let copy_buttons = document.getElementsByClassName('hljs-button')
  for (let i = 0; i < copy_buttons.length; i++) {
    copy_buttons[i].setAttribute('data-title', 'Copy code')
    copy_buttons[i].removeAttribute('onclick')

    let timerid: number | undefined = undefined // TODO

    copy_buttons[i].addEventListener('click', (event: Event) => {
      let button = copy_buttons[i];

      clearTimeout(timerid)
      event.stopPropagation()   // 阻止事件冒泡
      GM_setClipboard((button.parentNode as HTMLElement).innerText, 'text')  //TODO 去掉断言
      button.setAttribute('data-title', 'Copied!')
      timerid = setTimeout(() => {
        button.setAttribute('data-title', 'Copy code')
      }, 1000)
    })
  }

  // 展开需要关注博主阅读全文的内容
  // test: 需要订阅专栏的网址 https://blog.csdn.net/uote_e/article/details/131385801
  document.getElementById('article_content')?.removeAttribute("style")
  document.getElementsByClassName('hide-article-box')[0]?.remove()
}

// Purpose: Run existing article enhancements after the page has loaded. Generated by Codex
function startArticle(): void {
  // 保留原有文章增强逻辑的异常处理。
  main().catch(reportError)
// 结束文章启动函数。
}
// Purpose: Report article enhancement failures. Modified by Codex
function reportError(err: unknown): void {
  // 输出原有错误信息。
  console.error(err)
// 结束错误处理函数。
}
// 页面已经加载时直接启动，否则等待页面加载以兼容原来的运行时机。
if (document.readyState === 'complete') startArticle()
// 注册一次性的加载回调。
else window.addEventListener('load', startArticle, { once: true })
